baseurl: https://nostalgiadelreino.net
languageCode: es
theme: hugo-theme-stack
paginate: 3
title: Nostalgia del Reino
copyright: Juan Ignacio Gil Gómez

# Theme i18n support
# Available values: es
DefaultContentLanguage: es

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: mastodon
          name: Mastodon
          url: https://mastodon.floe.earth/@juanignaciogil
          params:
              icon: mastodon
        - identifier: linkedin
          name: Linkedin
          url: https://www.linkedin.com/in/juanignaciogilgomez/
          params:
              icon: linkedin
        - identifier: telegram
          name: Telegram
          url: https://t.me/+ZbUyYRa5oGAxMzQ8
          params:
              icon: telegram
        - identifier: github
          name: GitHub
          url: https://github.com/JuanIgnacioGil
          params:
              icon: brand-github


permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon: img/favicon.ico

    footer:
        since: 2004
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        # emoji: 🍥
        # subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        avatar:
            enabled: true
            local: true
            src: img/authorimage.jpg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
